### ISSUE TITLE
Cannot import `torch_brain.models` (circular import)

### ISSUE THREAD

**Issue by vinamarora8** [neuro-galaxy/torch_brain#26]
I get the following error when I try to import `POYOPlus` or `torch_brain.models`

```
>>> from torch_brain.models import POYOPlus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/varora38/torch_brain_wa1/torch_brain/torch_brain/models/__init__.py", line 1, in <module>
    from .poyo_plus import POYOPlus, POYOPlusTokenizer
  File "/home/varora38/torch_brain_wa1/torch_brain/torch_brain/models/poyo_plus.py", line 20, in <module>
    from torch_brain.utils import (
  File "/home/varora38/torch_brain_wa1/torch_brain/torch_brain/utils/__init__.py", line 6, in <module>
    from .datamodules import DataModule
  File "/home/varora38/torch_brain_wa1/torch_brain/torch_brain/utils/datamodules.py", line 16, in <module>
    from torch_brain.models import POYOPlusTokenizer
ImportError: cannot import name 'POYOPlusTokenizer' from partially initialized module 'torch_brain.models' (most likely due to a circular import) (/home/varora38/torch_brain_wa1/torch_brain/torch_brain/models/__init__.py)
>>> import torch_brain.models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/varora38/torch_brain_wa1/torch_brain/torch_brain/models/__init__.py", line 1, in <module>
    from .poyo_plus import POYOPlus, POYOPlusTokenizer
  File "/home/varora38/torch_brain_wa1/torch_brain/torch_brain/models/poyo_plus.py", line 20, in <module>
    from torch_brain.utils import (
  File "/home/varora38/torch_brain_wa1/torch_brain/torch_brain/utils/__init__.py", line 6, in <module>
    from .datamodules import DataModule
  File "/home/varora38/torch_brain_wa1/torch_brain/torch_brain/utils/datamodules.py", line 16, in <module>
    from torch_brain.models import POYOPlusTokenizer
ImportError: cannot import name 'POYOPlusTokenizer' from partially initialized module 'torch_brain.models' (most likely due to a circular import) (/home/varora38/torch_brain_wa1/torch_brain/torch_brain/models/__init__.py)
```

**Comment by mazabou** [comment]
yes, I get the same error. This is because `poyo_plus.py` uses `torch_brain.utils` which itself uses `POYOPlusTokenizer` for the datamodule.

**Comment by vinamarora8** [comment]
Yeah. So for now, I will remove `datamodule` from `__init__` of `utils`. Does that sound good @mazabou?
